MOTIVATIONAL_SENTENCES = [
    "You are stronger than you think.",
    "Believe in yourself and your abilities.",
    "Every setback is a setup for a comeback.",
    "Success begins with a single step.",
    "You have the power to change your life.",
    "You are capable of achieving great things.",
    "The best is yet to come.",
    "Hard work pays off in the end.",
    "Keep moving forward, one step at a time.",
    "You are resilient and can overcome challenges.",
    "Challenges make you stronger.",
    "Dream big and chase your dreams.",
    "You are in control of your destiny.",
    "Your potential is limitless.",
    "Embrace failure as a stepping stone to success.",
    "The journey is as important as the destination.",
    "One step at a time, you can climb any mountain.",
    "Stay focused on your goals.",
    "Don't be afraid to take risks.",
    "You are not alone in your journey.",
    "Your efforts will be rewarded.",
    "You are a work in progress, and that's okay.",
    "Stay committed to your dreams.",
    "You have the ability to create your own happiness.",
    "Every day is a new opportunity.",
    "Your past does not define your future.",
    "Stay positive, even in difficult times.",
    "You have the strength to overcome any obstacle.",
    "Success is a journey, not a destination.",
    "You are worthy of love and respect.",
    "Trust in the process of life.",
    "You are the author of your own story.",
    "Keep your head up and your heart open.",
    "You are braver than you believe.",
    "Make today better than yesterday.",
    "You are a force of nature.",
    "Take a deep breath and keep putting one foot in front of the other.",
    "Find joy in the little things.",
    "You have the power to make a difference.",
    "Stay true to your values and beliefs.",
    "Success is a series of small efforts, consistently applied.",
    "The world is full of opportunities for you.",
    "Even the longest journey begins with a single step.",
    "You are a masterpiece in progress.",
    "Focus on progress, not perfection.",
    "You have the courage to face your fears.",
    "Believe in the beauty of your dreams.",
    "Focus on the present step, not the entire staircase.",
    "Keep your dreams alive.",
    "You are a warrior, not a worrier.",
    "Success is a mindset.",
    "You are on the path to greatness.",
    "Stay persistent in your pursuits.",
    "You are the architect of your future.",
    "Every day is a chance to start anew.",
    "You are the captain of your own ship.",
    "Stay patient and stay the course.",
    "You are a rising star.",
    "Believe in the power of positive thinking.",
    "You are a work of art in progress.",
    "Keep your eyes on the prize.",
    "You are the creator of your own destiny.",
    "Stay true to yourself and your dreams.",
    "You are a diamond in the rough.",
    "Embrace change and adapt to it.",
    "Keep pushing forward, no matter what.",
    "The only way to fail is to stop trying; keep pushing forward.",
    "You are a force to be reckoned with.",
    "Dreams do come true if you work for them.",
    "You are a shining example of resilience.",
    "Stay focused on your goals and dreams.",
    "You are a source of inspiration to others.",
    "Believe in your ability to overcome adversity.",
    "You are capable of achieving greatness.",
    "Stay determined and never give up.",
    "You are a masterpiece in the making.",
    "Success is a journey, not a destination.",
    "You are stronger than you think.",
    "Keep your head held high.",
    "You are a warrior, not a worrier.",
    "Believe in the magic of new beginnings.",
    "You are capable of amazing things.",
    "Stay positive, even in tough times.",
    "You are the author of your own story.",
    "Embrace the challenges that come your way.",
    "You are a work in progress, and that's okay.",
    "Keep your dreams alive and pursue them.",
    "The only way to fail is to stop trying; keep pushing forward.",
    "You have the power to shape your future.",
    "You are in control of your own destiny.",
    "Stay true to yourself and your values.",
    "You are a force of nature, unstoppable.",
    "Believe in yourself and your potential.",
    "You are a magnet for success and happiness.",
    "Stay persistent in your efforts.",
    "You are capable of achieving your dreams.",
    "Dream big and fearlessly chase your goals.",
    "You are resilient and can bounce back.",
    "Success is built on determination and hard work.",
    "You are a unique and amazing individual.",
    "Stay focused on what truly matters to you.",
    "You are a source of inspiration to others.",
    "Believe in the beauty of your dreams.",
    "You are on a path to greatness.",
    "Stay committed to your goals and aspirations.",
    "You have the strength to overcome any obstacle.",
    "You are worthy of love and happiness.",
    "Perseverance is your greatest asset; don't give up.",

]